// <auto-generated />
using System;
using DATOS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DATOS.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200524192506_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DOMINIO.ENTIDADES.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioNavigatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioNavigatorId");

                    b.ToTable("Administrador");
                });

            modelBuilder.Entity("DOMINIO.ENTIDADES.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioNavigatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioNavigatorId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("DOMINIO.ENTIDADES.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("DOMINIO.ENTIDADES.Administrador", b =>
                {
                    b.HasOne("DOMINIO.ENTIDADES.Usuario", "UsuarioNavigator")
                        .WithMany()
                        .HasForeignKey("UsuarioNavigatorId");
                });

            modelBuilder.Entity("DOMINIO.ENTIDADES.Cliente", b =>
                {
                    b.HasOne("DOMINIO.ENTIDADES.Usuario", "UsuarioNavigator")
                        .WithMany()
                        .HasForeignKey("UsuarioNavigatorId");
                });
#pragma warning restore 612, 618
        }
    }
}
